// ═══════════════════════════════════════════════════════════════════════════════
// VIBECODE CLI - Template Generators
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Get intake template with values filled
 */
export function getIntakeTemplate(projectName, description, sessionId) {
  const timestamp = new Date().toISOString();

  return `# 📥 INTAKE: ${projectName}

## Captured: ${timestamp}
## Session: ${sessionId}

---

## 🎯 Mô tả dự án

${description}

---

## 📋 Parsed Information

### Project Type
[To be detected by AI]

### Key Requirements
- [To be extracted from description]

### Target Users
[To be identified]

### Constraints
[To be noted]

---

## ✅ Status

- [x] Intake captured
- [ ] Ready for Blueprint

---

*Generated by Vibecode CLI v1.0*
`;
}

/**
 * Get blueprint template
 */
export function getBlueprintTemplate(projectName, sessionId) {
  const timestamp = new Date().toISOString();

  return `# 📘 BLUEPRINT: ${projectName}

## Session: ${sessionId}
## Created: ${timestamp}

---

## 🎯 Project Overview

| Field | Value |
|-------|-------|
| Type | [Fill in] |
| Name | ${projectName} |
| Goal | [Fill in] |

---

## 📐 Architecture

[Describe your architecture here]

---

## 🎨 Design System

### Colors
- Primary: #3B82F6
- Secondary: #10B981
- Accent: #F59E0B

### Typography
- Headings: Inter
- Body: Inter

---

## 💻 Tech Stack

- Framework: Next.js 14
- Styling: Tailwind CSS
- Database: [If needed]
- Auth: [If needed]

---

## 📁 File Structure

\`\`\`
src/
├── app/
├── components/
├── lib/
└── styles/
\`\`\`

---

## ✅ Checkpoint

- [ ] Structure approved
- [ ] Design approved
- [ ] Tech stack approved

---

*Generated by Vibecode CLI v1.0*
`;
}

/**
 * Get contract template with content extracted from intake and blueprint
 */
export function getContractTemplate(projectName, sessionId, intakeContent = '', blueprintContent = '') {
  const timestamp = new Date().toISOString();

  // Extract goal from intake (look for "Mô tả dự án" section)
  let goal = extractSection(intakeContent, '## 🎯 Mô tả dự án', '---') ||
             extractSection(intakeContent, '## Mô tả dự án', '---') ||
             '[Define your clear, specific goal here]';

  // Extract tech stack from blueprint
  let techStack = extractSection(blueprintContent, '## 💻 Tech Stack', '---') || '';

  // Extract architecture from blueprint
  let architecture = extractSection(blueprintContent, '## 📐 Architecture', '---') || '';

  // Extract file structure from blueprint
  let fileStructure = extractSection(blueprintContent, '## 📁 File Structure', '---') || '';

  // Generate deliverables from goal and architecture
  const deliverables = generateDeliverablesFromContent(goal, techStack, architecture);

  // Generate acceptance criteria from deliverables
  const acceptanceCriteria = generateAcceptanceCriteria(deliverables);

  // Generate in-scope items
  const inScopeItems = deliverables.map(d => `- [ ] ${d.item}`).join('\n');

  // Generate deliverables table
  const deliverablesTable = deliverables.map((d, i) =>
    `| ${i + 1} | ${d.item} | ${d.description} | ⬜ |`
  ).join('\n');

  return `# 📜 CONTRACT: ${projectName}

## Session: ${sessionId}
## Created: ${timestamp}
## Status: DRAFT
## Spec Hash: [hash when locked]

---

## 🎯 Goal

${goal.trim()}

---

## ✅ In-Scope

${inScopeItems || '- [ ] [Deliverable 1]\n- [ ] [Deliverable 2]\n- [ ] [Deliverable 3]'}

---

## ❌ Out-of-Scope

- Features not mentioned in goal
- Additional integrations not specified
- Performance optimization beyond MVP

---

## 📦 Deliverables

| # | Item | Description | Status |
|---|------|-------------|--------|
${deliverablesTable || '| 1 | [Item] | [Description] | ⬜ |'}

---

## ✔️ Acceptance Criteria

${acceptanceCriteria || '- [ ] [Criterion 1]\n- [ ] [Criterion 2]'}

---

## ⚠️ Risks & Mitigations

| Risk | Mitigation |
|------|------------|
| Dependencies unavailable | Use alternative packages |
| Scope creep | Strict contract adherence |

---

## 🔙 Rollback Plan

If build fails:
1. Revert to last stable commit
2. Review contract requirements
3. Rebuild with corrections

---

*Generated by Vibecode CLI v1.1*
*Lock this contract with \`vibecode lock\` when ready*
`;
}

/**
 * Extract a section from markdown content
 */
function extractSection(content, startMarker, endMarker) {
  if (!content) return null;

  const startIndex = content.indexOf(startMarker);
  if (startIndex === -1) return null;

  const contentStart = startIndex + startMarker.length;
  const endIndex = content.indexOf(endMarker, contentStart);

  if (endIndex === -1) {
    return content.substring(contentStart).trim();
  }

  return content.substring(contentStart, endIndex).trim();
}

/**
 * Generate deliverables from content analysis
 */
function generateDeliverablesFromContent(goal, techStack, architecture) {
  const deliverables = [];

  // Parse goal for keywords to generate deliverables
  const goalLower = goal.toLowerCase();

  // Common patterns
  if (goalLower.includes('landing page') || goalLower.includes('website')) {
    deliverables.push({ item: 'Landing Page', description: 'Main landing page with hero section' });
    deliverables.push({ item: 'Responsive Design', description: 'Mobile-friendly layout' });
  }

  if (goalLower.includes('cli') || goalLower.includes('command')) {
    deliverables.push({ item: 'CLI Commands', description: 'Core command implementations' });
    deliverables.push({ item: 'Help System', description: 'Command help and documentation' });
  }

  if (goalLower.includes('api') || goalLower.includes('backend')) {
    deliverables.push({ item: 'API Endpoints', description: 'REST/GraphQL endpoints' });
    deliverables.push({ item: 'Data Models', description: 'Database models and schemas' });
  }

  if (goalLower.includes('auth') || goalLower.includes('login')) {
    deliverables.push({ item: 'Authentication', description: 'User login/logout flow' });
  }

  if (goalLower.includes('dashboard') || goalLower.includes('admin')) {
    deliverables.push({ item: 'Dashboard UI', description: 'Admin dashboard interface' });
  }

  // Always include core deliverables if none detected
  if (deliverables.length === 0) {
    deliverables.push({ item: 'Core Implementation', description: 'Main functionality as described' });
    deliverables.push({ item: 'UI/UX', description: 'User interface implementation' });
    deliverables.push({ item: 'Documentation', description: 'Usage documentation' });
  }

  // Add testing if not already included
  if (!deliverables.some(d => d.item.toLowerCase().includes('test'))) {
    deliverables.push({ item: 'Testing', description: 'Basic functionality tests' });
  }

  return deliverables;
}

/**
 * Generate acceptance criteria from deliverables
 */
function generateAcceptanceCriteria(deliverables) {
  if (!deliverables || deliverables.length === 0) {
    return '- [ ] All features work as expected\n- [ ] No console errors\n- [ ] Documentation complete';
  }

  const criteria = deliverables.map(d =>
    `- [ ] ${d.item} is complete and functional`
  );

  criteria.push('- [ ] No console errors or warnings');
  criteria.push('- [ ] Code is clean and documented');

  return criteria.join('\n');
}

/**
 * Get plan template
 */
export function getPlanTemplate(projectName, sessionId, specHash, contractContent) {
  const timestamp = new Date().toISOString();

  // Extract deliverables from contract
  const deliverablesMatch = contractContent.match(/## 📦 Deliverables[\s\S]*?\|[\s\S]*?(?=\n---|\n##|$)/);
  const deliverables = deliverablesMatch ? deliverablesMatch[0] : '[Extract from contract]';

  return `# 📋 EXECUTION PLAN: ${projectName}

## Session: ${sessionId}
## Created: ${timestamp}
## Spec Hash: ${specHash}
## Status: ACTIVE

---

## 🎯 Objective

Execute the locked contract deliverables in order.

---

## 📦 Deliverables from Contract

${deliverables}

---

## 🔧 Execution Steps

| Step | Task | Command/Action | Status |
|------|------|----------------|--------|
| 1 | Setup | Initialize project structure | ⬜ |
| 2 | Core Build | Implement main functionality | ⬜ |
| 3 | Styling | Apply design system | ⬜ |
| 4 | Testing | Run tests and validate | ⬜ |
| 5 | Review | Check against acceptance criteria | ⬜ |

---

## 📝 Notes

- Follow contract scope strictly
- Capture evidence for each step
- No scope creep allowed

---

## ⏱️ Time Tracking

| Phase | Started | Completed | Duration |
|-------|---------|-----------|----------|
| Build | ${timestamp} | - | - |
| Review | - | - | - |

---

*Generated by Vibecode CLI v1.1*
`;
}

/**
 * Get coder pack template - instructions for AI coder
 */
export function getCoderPackTemplate(projectName, sessionId, specHash, contractContent, blueprintContent, intakeContent = '') {
  const timestamp = new Date().toISOString();

  // Extract the goal from intake for quick reference
  const goalMatch = intakeContent.match(/## 🎯 Mô tả dự án\s*([\s\S]*?)(?=---|##|$)/);
  const projectGoal = goalMatch ? goalMatch[1].trim() : 'See contract for details';

  return `# 🏗️ CODER PACK: ${projectName}

## Session: ${sessionId}
## Generated: ${timestamp}
## Spec Hash: ${specHash}

---

## ⚠️ IMPORTANT - READ FIRST

You are the **Thợ (Builder)**. Your job is to execute the locked contract exactly as specified.

**Rules:**
1. Do NOT add features not in the contract
2. Do NOT modify the contract
3. Capture evidence of your work
4. Report any blockers immediately

---

## 🎯 PROJECT GOAL (Quick Reference)

${projectGoal}

---

## 📜 CONTRACT (LOCKED)

${contractContent}

---

## 📘 BLUEPRINT REFERENCE

${blueprintContent || '[No blueprint provided - follow contract specifications]'}

---

## 📥 ORIGINAL INTAKE

${intakeContent || '[No intake provided]'}

---

## 🔧 BUILD INSTRUCTIONS

1. Read the contract deliverables table
2. Implement each item in order
3. For each deliverable:
   - Create/modify the required files
   - Test the implementation
   - Mark as complete
4. Capture evidence:
   - Screenshots if UI
   - Terminal output if CLI
   - Test results if automated

---

## 📁 Evidence Collection

Save evidence to: \`.vibecode/sessions/${sessionId}/evidence/\`

Required evidence:
- \`changes.diff\` - Git diff of all changes
- \`build.log\` - Terminal output during build
- \`screenshots/\` - Visual evidence if applicable

---

## ✅ Completion Checklist

- [ ] All deliverables implemented
- [ ] All acceptance criteria met
- [ ] Evidence captured
- [ ] No scope creep

---

*Run \`vibecode build --complete\` when finished*

*Generated by Vibecode CLI v1.1*
`;
}

/**
 * Get build report template
 */
export function getBuildReportTemplate(projectName, sessionId, specHash, startTime, endTime, evidence) {
  const duration = endTime ? Math.round((new Date(endTime) - new Date(startTime)) / 1000 / 60) : 'In progress';

  return `# 🏗️ BUILD REPORT: ${projectName}

## Session: ${sessionId}
## Spec Hash: ${specHash}
## Status: ${endTime ? 'COMPLETED' : 'IN PROGRESS'}

---

## ⏱️ Timeline

| Metric | Value |
|--------|-------|
| Started | ${startTime} |
| Completed | ${endTime || '-'} |
| Duration | ${duration} ${endTime ? 'minutes' : ''} |

---

## 📁 Evidence Collected

${evidence.hasDiff ? '- ✅ changes.diff' : '- ⬜ changes.diff'}
${evidence.hasLog ? '- ✅ build.log' : '- ⬜ build.log'}
${evidence.screenshots > 0 ? `- ✅ ${evidence.screenshots} screenshots` : '- ⬜ No screenshots'}

---

## 📊 Summary

- Files changed: ${evidence.filesChanged || 'N/A'}
- Lines added: ${evidence.linesAdded || 'N/A'}
- Lines removed: ${evidence.linesRemoved || 'N/A'}

---

## 🔍 Next Steps

${endTime ? '1. Run `vibecode review` to validate build' : '1. Continue building\n2. Run `vibecode build --complete` when done'}

---

*Generated by Vibecode CLI v1.1*
`;
}

/**
 * Get review report template
 */
export function getReviewReportTemplate(projectName, sessionId, specHash, checks, passed) {
  const timestamp = new Date().toISOString();

  const checksList = checks.map(c =>
    `| ${c.name} | ${c.passed ? '✅ PASS' : '❌ FAIL'} | ${c.message || '-'} |`
  ).join('\n');

  return `# 🔍 REVIEW REPORT: ${projectName}

## Session: ${sessionId}
## Spec Hash: ${specHash}
## Reviewed: ${timestamp}
## Result: ${passed ? '✅ PASSED' : '❌ FAILED'}

---

## 📋 Automated Checks

| Check | Result | Details |
|-------|--------|---------|
${checksList}

---

## ✔️ Acceptance Criteria Review

[Manually verified against contract]

---

## 📊 Summary

- Total checks: ${checks.length}
- Passed: ${checks.filter(c => c.passed).length}
- Failed: ${checks.filter(c => !c.passed).length}

---

## 🎯 Verdict

${passed ? `
**REVIEW PASSED**

All checks passed. Ready for shipping.
Run \`vibecode snapshot\` to create release.
` : `
**REVIEW FAILED**

Some checks failed. Please fix the issues and run \`vibecode build\` again.
`}

---

*Generated by Vibecode CLI v1.1*
`;
}

/**
 * Get manifest template for release
 */
export function getManifestTemplate(projectName, version, specHash, sessionId, files) {
  const timestamp = new Date().toISOString();

  return {
    name: projectName,
    version: version,
    specHash: specHash,
    sessionId: sessionId,
    timestamp: timestamp,
    generator: 'vibecode-cli@1.1.0',
    files: files,
    status: 'SHIPPED'
  };
}
